### ISSUE TITLE
Error when destroying a unit

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/basic-auth-service-charm#1]
I destroyed the second unit of a two-unit deployment of basic-auth-service, ```basic-auth-service/1```, and got this hook error:

```
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed Traceback (most recent call last):
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/var/lib/juju/agents/unit-basic-auth-service-1/charm/hooks/nrpe-external-master-relation-departed", line 19, in <module>
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     main()
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     bus.dispatch()
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 423, in dispatch
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     _invoke(other_handlers)
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 406, in _invoke
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     handler.invoke()
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 280, in invoke
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     self._action(*args)
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/var/lib/juju/agents/unit-basic-auth-service-1/charm/reactive/basic_auth.py", line 117, in remove_nrpe_config
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     nrpe_setup.remove_check(shortname=service)
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charmhelpers/contrib/charmsupport/nrpe.py", line 274, in remove_check
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     check = Check(*args, **kwargs)
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed   File "/usr/local/lib/python3.5/dist-packages/charmhelpers/contrib/charmsupport/nrpe.py", line 148, in __init__
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed     Check.shortname_re))
2017-05-24 20:58:02 INFO nrpe-external-master-relation-departed charmhelpers.contrib.charmsupport.nrpe.CheckException: shortname must match [A-Za-z0-9-_]+$
```

Is this [charm-helpers #1693296](https://bugs.launchpad.net/charm-helpers/+bug/1693296)? I thought we were using the [workaround](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py#L56)

**Comment by albertodonato** [comment]
@panlinux it's the same error, but I initially patched the regexp only in one hook.
It's done at the top level now.
